<script>
(function( $ ) {
    
    // Extend the autocomplete widget, using our own application namespace.
    $.widget( "app.autocomplete", $.ui.autocomplete, {

        // The _renderItem() method is responsible for rendering each
        // menu item in the autocomplete menu.
        _renderItem: function( ul, item ) {

            // We want the rendered menu item generated by the default implementation.
            var result = this._super( ul, item );

            // If there is logo data, add our custom CSS class, and the specific
            // logo URL.
            if ( item.logo ) {
                result.find( "a" )
                      .addClass( "ui-menu-item-icon" )
                      .css( "background-image", "url(" + item.logo + ")" );
            }

            return result;

        }

    });

})( jQuery );

$(function() {
    
    // Build our autocomplete widget using a source array. Notice that each object
    // in the array has a &quot;logo&quot; property? We can add any properties we want here.
    $( "#lib" ).autocomplete({
        source: [
            {
                label: "Boruto",
                logo: "https://1.bp.blogspot.com/-qjUwt_DbbR0/WZR7nTKrA4I/AAAAAAAAB-8/WZVY8JXHosYOjjDW5nYeOedxDAcBOBTpQCLcBGAs/s320/boruto-naruto-next-generations-episodios.jpg",
            },
            {

                label: "Black Clover",
                logo: "https://3.bp.blogspot.com/-Uungn5NNgAc/Wc_SDDtzPHI/AAAAAAAADeg/gQo2VZtSGVQ5UVD-dveGvAERhzoZO63uQCLcBGAs/s1600/black-clover-2017-todos-os-episodios-online.jpg"
            },
            {
                label: "Dragon Ball Super",
                logo: "https://4.bp.blogspot.com/-k_hS3m4JFgo/WYeTHJb4YjI/AAAAAAAABgs/H_RDLsV6r6AHZYSbhYhQFcXwFIooQZcAACLcBGAs/s320/dragon-ball-super-todos-os-episodios-dublado-animes-one-hd.jpg"
            },
            {
                label: "Nanatsu No Taizai",
                logo: "https://4.bp.blogspot.com/-UEbeu6L7hAU/Wlo6c8FfD7I/AAAAAAAAIDc/sY7ERiFgTSwDPDiozhpVyMRL02C2vC1sACLcBGAs/s320/Nanatsu_no_Taizai__Imashime_no_Fukkatsu.jpg"
            },
            {
               label: "One Punch Man&quot;,
                logo: "https://2.bp.blogspot.com/-lajKe2CNpjc/WZY5DDk45-I/AAAAAAAACCQ/GI8MdSvaCLAStCDYOSf1exMKBDqsoAWngCLcBGAs/s320/one-punch-man-dublado-todos-os-episodios.jpg"
            },
            {
               label: "Yowamushi Pedal: Glory Line",
                logo: "https://2.bp.blogspot.com/-9mqGJK6PtO4/WlQzGh_5OkI/AAAAAAAAH3s/xDwkOpJGzLsGUEY69l9H1ra-plPX7UxwgCLcBGAs/s320/yowamushi-pedal-glory-line.jpg"
             },
             {

                label: "One Piece",
                logo: "https://1.bp.blogspot.com/-rPiIN1z-afs/WadBUphHpmI/AAAAAAAACfA/fKMw3C9JIjwoonqCZ9BvDAsuvAthQKsDQCLcBGAs/s320/One-Piece-anime-zou-arc-poster-promo.jpeg"
            },
            {
               label: "Karakai Jouzu no Takagi-san",
                logo: "https://1.bp.blogspot.com/-eKn66ZzPceg/WlPlDHt09BI/AAAAAAAAH2k/Od-OvMlOPyA38pYeiediua5LZ6RkmI1DACLcBGAs/s320/karakai-jouzu-no-takagi-san.jpg"
            },
            {
               label: "Ryuuou no Oshigoto!",
                logo: "https://2.bp.blogspot.com/-1YKm7771mGs/WlPimGLQHpI/AAAAAAAAH2c/rHznXibhhmQC41FtcaZIDs2FcEWfiELCwCLcBGAs/s320/ryuuou-no-oshigoto.jpg"
            },
            {
               label: "Basilisk: Ouka Ninpouchou",
                logo: "https://2.bp.blogspot.com/-WLkWuPHRARs/WlQwcqCOmpI/AAAAAAAAH3U/L3WPwI2u778Rnl35wIlpsE06_sDabfL4ACLcBGAs/s320/basilisk-ouka-ninpouchou.jpg"
            },
            {
               label: "Cupid&#8217;s Chocolates 2",
                logo: "https://1.bp.blogspot.com/-0zAwKjVbDJc/WlVBiO9GGeI/AAAAAAAAH5Q/sGqj58guEgYmmqa45p46i118LMVtZ0lXgCLcBGAs/s320/Aishen_Qiaokeli-ing_2nd_Season.jpg"            },
            {
               label: "Overlord II",
                logo: "https://1.bp.blogspot.com/-ZpYg7sXEgCM/WkqUP7kFh9I/AAAAAAAAHpE/6anfWT_TV-QCpLTpbwO3EIm4LFoLofiXgCLcBGAs/s320/overlord-2.jpg"
            },
            {
               label: "Sora yori mo Tooi Basho",
                logo: "https://4.bp.blogspot.com/-vKercMB7XYo/WkuxMfiM3xI/AAAAAAAAHpk/ffXovcPWyKMELup8MHqros2lnqnEzB5zwCLcBGAs/s320/Sora%2Byori%2Bmo%2BTooi%2BBasho.jpg"
            },
            {
               label: "Cardfight!! Vanguard G: Z",
                logo: "https://4.bp.blogspot.com/-zMJ8Vzo0skQ/WkVlVC6i2xI/AAAAAAAAHkE/6aJO4pCVlCUic3fMFquuvtqBMtzxsPpNgCLcBGAs/s320/cardfight-vanguard-g-z.jpg"
            },
            {
               label: "Yu-Gi-Oh! VRAINS",
                logo: "http://image.phimmoi.net/film/5272/poster.medium.jpg"
            },
            {
               label: "Hitori no Shita: The Outcast 2",
                logo: "https://2.bp.blogspot.com/-JVlTPyUhnac/WlY-80gKYAI/AAAAAAAAH6M/8OJcrJICOfA65Ma5709wrrbd3ELBe4ncgCLcBGAs/s320/Hitori_no_Shita__The_Outcast_2nd_Season.jpg"
            },
            {
               label: "Koi wa Ameagari no You ni",
                logo: "https://4.bp.blogspot.com/-SFWpufdQoi0/WlaEk-0bOvI/AAAAAAAAH68/n_m_Rw2_o983kySneJxa8AF4aBSvxZrPgCLcBGAs/s320/Koi_wa_Ameagari_no_You_ni.jpg"
            },
            {
               label: "Emiya-san Chi No Kyou No Gohan",
                logo: "https://1.bp.blogspot.com/-1v55bwf-RiI/Wk2JsG4GYRI/AAAAAAAAHtE/dyztqhUpMhQHWureEOd_bvNFvNjvLpbbQCLcBGAs/s320/Emiya-san_Chi_no_Kyou_no_Gohan.jpg"
            },
            {
               label: "Kaiju Girls 2",
                logo: "https://1.bp.blogspot.com/-43Sah7i_nkM/WmE8EoNhu-I/AAAAAAAAIQQ/tiKShCaL7Bg9oXoBgcouhNtmbu5eGaY0QCLcBGAs/s320/Kaijuu_Girls__Ultra_Kaijuu_Gijinka_Keikaku_2nd_Season.jpg"
            },
            {
               label: "Ramen Daisuki Koizumi-san",
                logo: "https://3.bp.blogspot.com/-gw9Qe78brSs/Wk5UY15r1fI/AAAAAAAAHto/EtSH7Qr0kUMS32QC55S6WuD8m5J1rebhwCLcBGAs/s1600/Ramen%2BDaisuki%2BKoizumi-san.jpg"
            },
            {
               label: "Yuru Camp",
                logo: "https://4.bp.blogspot.com/-V0QdVWevXsI/Wk5V7-aoq0I/AAAAAAAAHt8/0pixOaOAupMYaFoZY9FvNFcdBgngi-b6gCLcBGAs/s1600/Yuru%2BCamp%25E2%2596%25B3.jpg"
            },
            {
               label: "The King of Fighters: Destiny",
                logo: "https://3.bp.blogspot.com/-Yrg43lOUFbk/WcRPMXk5X6I/AAAAAAAADMs/KHYixew7TmUS3SZUIkvgrRV50cPIbBLZgCLcBGAs/s1600/the-king-of-fighters-destiny-os-episodios-online.jpg"
            },
            {
               label: "Grancrest Senki",
                logo: "https://3.bp.blogspot.com/-sK0T3hXXTSw/Wk-uAn-m8XI/AAAAAAAAHvE/0epPQ4HVAqsuO9SLHaRVfoaIZSiBn7XpACLcBGAs/s320/Grancrest_Senki.jpg"
            },
            {
               label: "Toji no Miko",
                logo: "https://3.bp.blogspot.com/-dwP917M7AlM/Wk-lnTBJSTI/AAAAAAAAHuU/nxGpGof9BZIuiI4G-SfB9wXYY5GHE0sWwCLcBGAs/s320/Toji_no_Miko.jpg"
            },
            {
               label: "Ito Junji: Collection",
                logo: "https://1.bp.blogspot.com/-Z2y1BC3-mOo/Wk-sXK8cuVI/AAAAAAAAHuw/Oa1B7AZlkRU0AGarxbzTtx8nw0mM9auWACLcBGAs/s320/Ito_Junji__Collection.jpg"
            },
            {
               label: "Killing Bites",
                logo: "https://2.bp.blogspot.com/-iBJsnlC2QBA/Wll2Y4HSGWI/AAAAAAAAICw/kp3fKRlM0BIXzjPTLIRuV_TCjCwpj9ujgCLcBGAs/s320/Killing_Bites.jpg"
            },
            {
               label: "Pop Team Epic (Poputepipikku)",
                logo: "https://4.bp.blogspot.com/-NmMmPvdI7J8/WlER49CYLiI/AAAAAAAAHxk/994CSrkIPKkRwV9Ht8gEZeGkt8lLRQhzgCLcBGAs/s320/Poputepipikku.jpg"
            },
            {
               label: "Slow Start",
                logo: "https://2.bp.blogspot.com/-brZwldZ5koc/WlETajngHhI/AAAAAAAAHxw/aeeD48pmxncn6HkQkrLVxyxV0EQIjBuwQCLcBGAs/s320/Slow_Start.jpg"
            },
            {
               label: "Citrus",
                logo: "https://3.bp.blogspot.com/-Wvf1TbvZ1sg/WlEBxk9cIrI/AAAAAAAAHww/JsPVQDNPXwwtv2Dsume8Y65iq2Y3KS3-gCLcBGAs/s320/Citrus.jpg"
            },
            {
               label: "Sanrio Danshi",
                logo: "https://3.bp.blogspot.com/-dGxpMxaVWuQ/WlDvMJpF7RI/AAAAAAAAHwM/V0jh_tZqFL8IBr7tN_bvXkXob8lCom2TACLcBGAs/s320/Sanrio_Danshi.jpg"
            },
            {
               label: "Kokkoku",
                logo: "https://2.bp.blogspot.com/-L7LsTjlUNfs/WlKGQ-YhRDI/AAAAAAAAH1w/okFfcYjaO709XY2sytU7tnTlKG96lstzACLcBGAs/s320/Kokkoku.jpg"
            },
            {
               label: "Mitsuboshi Colors",
                logo: "https://1.bp.blogspot.com/-1b6k5MimGN4/WlJvXwj26KI/AAAAAAAAH0s/bjXqGKLTEGwxKX-0rgunCWXlvxqQOzwTgCLcBGAs/s320/Mitsuboshi_Colors.jpg"
            },
            {
               label: "Gintama.: Shirogane no Tamashii-hen",
                logo: "https://3.bp.blogspot.com/-hMeD0SWvTQ0/WlJ-6dOZ1SI/AAAAAAAAH1U/UTuiIO9yA0YnZTJ0E46nNbF6p1qlQeP3ACLcBGAs/s1600/Gintama__Shirogane_no_Tamashii-hen.jpg"
            },
            {
               label: "Gakuen Babysitters",
                logo: "https://2.bp.blogspot.com/-qxxz9aKqMZY/WlJN1DB95ZI/AAAAAAAAHz4/i8OBcLny7pkSXhADnsbDKYTpd4s3EuGkwCLcBGAs/s320/gakuen-babysitters.jpg"
            },
            {
               label: "25-sai no Joshikousei",
                logo: "https://3.bp.blogspot.com/-BnghLhrfM8U/WlgHeqrGIBI/AAAAAAAAH-o/GX4KiVaB1wcu5G6hI-Hzsb5fBnav897xQCLcBGAs/s320/25-sai_no_Joshikousei.jpg"
            },
            {
               label: "Hakata Tonkotsu Ramens",
                logo: "https://3.bp.blogspot.com/-RFxcxj3cBg8/Wljh45RN5RI/AAAAAAAAIAc/92469IVoH58SvxKpPhYfPOQdifT9ZuHgwCLcBGAs/s320/Hakata_Tonkotsu_Ramens.jpg"
            },
            {
               label: "Hakumei to Mikochi",
                logo: "https://3.bp.blogspot.com/-Qcb2MJn_9jU/WljtuI0bboI/AAAAAAAAIA8/mCfw6aC3F88HUtOIU7lsGKfLf_NATPqcACLcBGAs/s320/Hakumei_to_Mikochi.jpg"
            },
            {
               label: "3-gatsu no Lion 2",
                logo: "https://3.bp.blogspot.com/-t_3ww92U4kU/WeP4vOA9uQI/AAAAAAAAEWA/soyCKCDjs9woxR2wtBd1uiE6CSr1sZM_QCLcBGAs/s320/3-gatsu%2Bno%2BLion%2B2nd%2BSeason.jpg"
            },
            {
               label: "Violet Evergarden (Dublado)",
                logo: "https://1.bp.blogspot.com/-imStxdCvIRg/WlfijEWPq5I/AAAAAAAAH-I/tw-HGNMpMA4oj3StB8mFebeyWHoZw_bcgCLcBGAs/s320/Violet_Evergarden_dublado.jpg"
            },
            {
               label: "Violet Evergarden",
                logo: "https://4.bp.blogspot.com/-1f9E-RtO0FU/WlaviS7qWvI/AAAAAAAAH7Y/0f-iaMEV0KkGOPIWxNgepY2EUqAhFhXtACLcBGAs/s320/Violet_Evergarden.jpg"
            },
            {
               label: "Garo: Vanishing Line",
                logo: "https://1.bp.blogspot.com/-S4qvlFFQnS0/Wc_TI8OpFII/AAAAAAAADeo/7-x6P_zvniQhvgWGOmgQdCVGCz1uG57RgCLcBGAs/s1600/garo-vanishing-line-todos-os-episodios-online.png"
            },
            {
               label: "Hakyuu Houshin Engi",
                logo: "https://3.bp.blogspot.com/-1Bpa2-wH30o/Wlklk5esw4I/AAAAAAAAIBs/tCc1tM19Q64B1I08Jqs-zLOETABa_ZuhwCLcBGAs/s320/Hakyuu_Houshin_Engi.jpg"
            },
            {
               label: "Miira no Kaikata",
                logo: "https://3.bp.blogspot.com/-68JXga0RKPU/Wlfb89hBGfI/AAAAAAAAH9w/fIuLAI0gZLwzoI97WF8Xm-QXNUiZp8v7ACLcBGAs/s1600/Miira%2Bno%2BKaikata.jpg"
            },
            {
               label: "Saiki Kusuo no Psi-nan 2",
                logo: "https://1.bp.blogspot.com/-wi4FRBtHFAo/WmTs0Tpt6GI/AAAAAAAAIY8/m_y0EmBHHvY9sIRnzExVBSy7QGrg3lGmwCLcBGAs/s320/Saiki_Kusuo_no_%25CE%25A8-nan_2.jpg"
            },
            {
               label: "Marchen Madchen",
                logo: "https://2.bp.blogspot.com/-BJvJ9FDHEY8/WleY_f0eZ1I/AAAAAAAAH80/GDAEwIuh8gcUNylNoczU-irZZRWb8MYZgCLcBGAs/s320/M%25C3%25A4rchen_M%25C3%25A4dchen.jpg"
            },
            {
               label: "Death March kara Hajimaru Isekai Kyousoukyoku",
                logo: "https://4.bp.blogspot.com/-snvPBeHi5uQ/WlecsY46WeI/AAAAAAAAH9E/nKW_VTxrhAUlmcW8DQdrq4Z6W-2lQ0MYACLcBGAs/s320/Death_March_kara_Hajimaru_Isekai_Kyousoukyoku.jpg"
            },
            {
               label: "Dame x Prince Anime Caravan",
                logo: "https://4.bp.blogspot.com/-07ewRoT0Ru4/Wlaw0itqDHI/AAAAAAAAH7k/ylHAL1iI3w883IuBLbqNGHgTfc6PwF6sgCLcBGAs/s320/Dame_x_Prince_Anime_Caravan.jpg"
            },
            {
               label: "Beatless",
                logo: "https://1.bp.blogspot.com/-FnKCfoSUk2I/WllofwJ3QcI/AAAAAAAAICg/HXNJw6un7RY50VsOurU4Bm15twdBanzPQCLcBGAs/s320/Beatless.jpg"
            },
            {
               label: "Fairy Tail",
                logo: "http://assistindoanimesonline.com/img/animes-dublados-legendados/F/Fairy-Tail.png"
            },
            {

               label: "Death Note (Dublado)",
                logo: " https://i.pinimg.com/564x/db/08/16/db08169b0cfa315452a4f364899d4db2--death-note-anime-anime-eyes.jpg"
            },
            {
               label: "Bleach (Dublado)",
                logo: "https://i16.photobucket.com/albums/b44/kyogrl/bleach-001.jpg" 

             },
            {
               label: "Nanatsu no Bitoku",
                logo: "https://1.bp.blogspot.com/-2NQ4mDQNjCA/WmufFtBMsoI/AAAAAAAAIiY/iUn2H7ocHqwlln2KT9NmCfwIityKzHJDQCLcBGAs/s72-c/Nanatsu_no_Bitoku.jpg" 

             }
        ]
    });
    
});
</script>
